In [ ]:
import pandas as pd
bucket = [3.14, 'pi', 2.718]
series = pd.Series(bucket)
print(series)

0     3.14
1       pi
2    2.718
dtype: object


In [ ]:
import pandas as pd
items = { 'col1' : [1,2,3], 'col2' : [3,4,5]}
df_from_dict =  pd.DataFrame(items)
print(df_from_dict)

   col1  col2
0     1     3
1     2     4
2     3     5


In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
print(df.head)'''

In [ ]:
'''
import pandas as pd
df = pd.read_csv('data.csv' , delimiter = ';')
print(df.head())

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
value = df.iloc[3,4]
print(value)

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
age_filtered = df['Age'] > 23
result = df[age_filtered]
print(result)

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
mean = df['Age'].mean()
print(mean)

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
min_amount = df['Credit amount'].min()
print(min_amount)

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
group = df.groupby('Sex')
min_age = group['Age'].min()
print(min_age)

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
merged = pd.merge(df,df,on='Sex',how='inner')
print(merged)

In [ ]:
import numpy as np

sales_data = [200, 450, 150, 400, 500, 700]

# Write your code below
sales_array = np.array(sales_data)
min_index = np.argmin(sales_array)
max_index= np.argmax(sales_array)
print(min_index)
print(max_index)

2
5


In [ ]:
import numpy as np

# Write your code below
sales_data = [100,150,200,250,300]
new_sale = 350
updated_sales_data= np.append(sales_data, new_sale)
print(updated_sales_data)

[100 150 200 250 300 350]


In [ ]:
import numpy as np

# Write your code below
team_a_scores = np.array([80,85,90,95,100])
team_b_scores = np.array([70,75,80,85,90])
all_team_scores = np.concatenate((team_a_scores, team_b_scores))
print(all_team_scores)

[ 80  85  90  95 100  70  75  80  85  90]


In [ ]:
import numpy as np

# Write your code below
daily_temperatures = np.array([72,75,78,70,68])
total_temperature = np.sum(daily_temperatures)
print(total_temperature)

363


In [ ]:
import numpy as np

# Write your code below
exam_scores = ([85,90,88,92,87])
average_score = np.mean(exam_scores)
print(average_score)

88.4


In [ ]:
import numpy as np

# Write your code below
age_data = ([25,30,35,40,45])
median_age = np.median(age_data)
print(median_age)

35.0


In [ ]:
import numpy as np

# Write your code below
sales_data = [150,200,250,300,350]
array = np.array(sales_data)
sliced_array = array[1:4]
print(sliced_array)

[200 250 300]


In [ ]:
import numpy as np
demo_array = np.arange(0,10)
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
import pandas as pd
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']
print(flowers)

lily     2
rose     3
daisy    5
lotus    4
dtype: int64



customer	category	important	sales
0	101	cat2	yes 	123
1	102	cat2	no 	52
2	103	cat1	yes 	214
3	104	cat3	yes	663

In [ ]:
import numpy as np
ab = np.array([1,10,21,35,72])
print(ab)

[ 1 10 21 35 72]


In [ ]:
import numpy as np
ab = np.array([[9,8,7],[6,5,4],[3,2,1]])
cd = np.arange(start=1, stop=10, step=1).reshape(3,3)
print(cd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])
mat_aver = mat.mean()
print(mat_aver)

131.66666666666666


In [ ]:
import numpy as np
a = np.arange(0,20)
print(a[2:7])

[2 3 4 5 6]


In [ ]:
import numpy as np
ab = np.cos([0, 1, 2, 3, 4])
print(ab)

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [ ]:
import numpy as np
list_1 = [1,2,3]
list_2 = [4,5,6]
new_list = list_1 + list_2
print(new_list)
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
print(new_array)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
import numpy as np
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[1] = 5
print(mat)

[[1 2 1]
 [5 5 5]
 [1 8 9]]


In [ ]:
import numpy as np
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

21


In [ ]:
import numpy as np
ab = np.identity(2*2)
print(ab)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
ab = np.identity(2)
print(ab)

[[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np
ab = np.ones((2,2))
print(ab)

[[1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
dot_prod = np.dot(n1,n2)
print(dot_prod)

[[1786 1880 3017]
 [2725 2933 4712]
 [3862 4220 6785]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')



Mounted at /content/drive


In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/books.csv')
print(df)

                                                  title  \
0                           The Hunchback of Notre-Dame   
1     La Cucina Di Lidia: Recipes and Memories from ...   
2                                     Breach of Promise   
3                     Brief Interviews with Hideous Men   
4     The Killing Dance (Anita Blake  Vampire Hunter...   
...                                                 ...   
4995                                 The Complete Works   
4996                               Shipwreck (Island I)   
4997           Every Night Italian: Every Night Italian   
4998                                     Go Down  Moses   
4999  The Avignon Quintet: Monsieur  Livia  Constanc...   

                           author  average_rating         isbn13  \
0                     Victor Hugo            4.00  9780345472427   
1     Lidia Matticchio Bastianich            4.14  9780767914222   
2                James Scott Bell            4.00  9780310243878   
3            David 

In [ ]:
print(df.head())

                                               title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13 language_code  \
0                  Victor Hugo            4.00  9780345472427         en-US   
1  Lidia Matticchio Bastianich            4.14  9780767914222         en-GB   
2             James Scott Bell            4.00  9780310243878           eng   
3         David Foster Wallace            3.86  9780349111889           eng   
4          Laurell K. Hamilton            4.13  9780425209066         en-US   

   num_pages  ratings_count  text_reviews_count          publisher  year  
0      534.0            140                  22     Modern Library  2004  
1      288.0             48           

In [ ]:
dimensions = df.shape
print(dimensions)

(5000, 10)


In [ ]:
df.describe()

,average_rating,isbn13,num_pages,ratings_count,text_reviews_count,year
count,5000.000000,5.000000e+03,4967.000000,5.000000e+03,5000.000000,5000.000000
mean,3.931932,9.752758e+12,341.094021,2.017549e+04,592.688600,2000.131800
std,0.348741,5.129254e+11,230.986115,1.175026e+05,2539.539004,8.069043
min,0.000000,8.987060e+09,1.000000,0.000000e+00,0.000000,1913.000000
25%,3.770000,9.780345e+12,200.000000,1.050000e+02,9.000000,1998.000000
50%,3.960000,9.780571e+12,304.000000,7.915000e+02,49.000000,2003.000000
75%,4.140000,9.780871e+12,416.500000,5.348750e+03,249.000000,2005.000000
max,5.000000,9.789879e+12,3342.000000,2.457092e+06,55843.000000,2019.000000


In [ ]:
object_count = (df.dtypes == 'object').sum()
print(object_count)

4


In [ ]:
count = (df['average_rating'] > 4).sum()
print(f"Total books with a rating > 4: {count}")

Total books with a rating > 4: 2115


In [ ]:
hidden_gems = df[(df['average_rating'] > 4.5) & (df['ratings_count'] < 10)]
print(hidden_gems)

                                                  title  \
63                                             鋼之鍊金術師 9   
178                                            鋼之鍊金術師 6   
224                             Stargirl LitPlans on CD   
454   Literature Circle Guide: Bridge to Terabithia:...   
584                       Falling Angels (Luc Actar #1)   
681        Fanning the Flame: Bible  Cross  and Mission   
696                  Tyrannosaurus Wrecks (Stanley  #1)   
741   The John Deere Two-Cylinder Tractor Encycloped...   
757   The American Campaign: U.S. Presidential Campa...   
1837  The Goon Show  Volume 4: My Knees Have Fallen ...   
1856                                          鋼之鍊金術師 10   
1960  Wissenschaft der Logik: Die Lehre Vom Begriff ...   
2244  Getting a Grip on the Basics: Building a Firm ...   
2496                               Come Away My Beloved   
3178  Organizational Architecture: Designs for Chang...   
3438         Bill Gates: Computer Legend (Famous Lives) 

In [ ]:
eng_mean = df[df['language_code'] == 'eng']['average_rating'].mean()
print(f"The mean rating for English books is : {eng_mean}")

The mean rating for English books is : 3.931142857142857


In [ ]:
language_stats = df.groupby('language_code')['average_rating'].mean()
print(language_stats)

language_code
en-GB    3.922523
en-US    3.914800
eng      3.931143
ger      3.979773
grc      2.366667
jpn      4.252381
lat      4.170000
mul      4.116000
spa      3.927938
Name: average_rating, dtype: float64


In [ ]:
df.head(1)

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.0,9780345472427,en-US,534.0,140,22,Modern Library,2004


In [ ]:
df.head()

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427,en-US,534.0,140,22,Modern Library,2004
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
2,Breach of Promise,James Scott Bell,4.00,9780310243878,eng,345.0,368,36,Zondervan,2004
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889,eng,273.0,18335,1155,Abacus,2000
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006


In [ ]:
first_five = df.iloc[0:5, 0:4]
print(first_five)

                                               title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13  
0                  Victor Hugo            4.00  9780345472427  
1  Lidia Matticchio Bastianich            4.14  9780767914222  
2             James Scott Bell            4.00  9780310243878  
3         David Foster Wallace            3.86  9780349111889  
4          Laurell K. Hamilton            4.13  9780425209066  


In [ ]:
one_four = df.loc[[1,4],['language_code', 'num_pages', 'ratings_count']]
print(one_four)

  language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524


In [ ]:
median_pages = df['num_pages'].median()
mean_pages = df['num_pages'].mean()
print(median_pages)
print(mean_pages)

304.0
341.0940205355345


In [ ]:
df.head()

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427,en-US,534.0,140,22,Modern Library,2004
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
2,Breach of Promise,James Scott Bell,4.00,9780310243878,eng,345.0,368,36,Zondervan,2004
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889,eng,273.0,18335,1155,Abacus,2000
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006


In [ ]:
count_2010 = (df['year']== 2010).sum()
print(count_2010)

15


In [ ]:
daw_authors = df[(df['publisher'] == 'DAW') & (df['average_rating'] > 4)]['author'].unique()
print(daw_authors)

['Mercedes Lackey' 'Sharon Green']


In [ ]:
count_500 = ((df['num_pages'] > 500) & (df['year'] > 2010)).sum()
print(count_500)

5


In [ ]:
Agatha_count = df['author'].str.contains('Agatha Christie',case=False,na=False).sum()
print(Agatha_count)

21


In [ ]:
spanish_count = ((df['language_code'] == 'spa') & (df['year'] > 2000)).sum()
print(spanish_count)

84
